# Generated by Django 5.0.6 on 2024-06-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='descriptionName',
            new_name='cityDescription',
        ),
    ]
