# Generated by Django 5.0.6 on 2024-06-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_descriptionname_tour_citydescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewName', models.CharField(max_length=100)),
                ('reviewEmail', models.EmailField(max_length=254)),
                ('reviewComment', models.TextField()),
                ('reviewRating', models.IntegerField()),
                ('reviewTour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touristName', models.CharField(max_length=100)),
                ('touristEmail', models.EmailField(max_length=254)),
                ('touristPhone', models.CharField(max_length=15)),
                ('touristAge', models.IntegerField()),
                ('touristTour', models.ManyToManyField(related_name='tourists', to='tour.tour')),
            ],
        ),
    ]
